# Generated by Django 5.0.6 on 2025-07-28 17:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adAdmin', '0002_remove_status_description_alter_status_name'),
        ('adCampaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adAdmin.status'),
        ),
    ]
