# Generated by Django 5.2.4 on 2025-08-24 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adCampaigns', '0002_accounttype_created_at_accounttype_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='default_publication',
        ),
        migrations.RemoveField(
            model_name='account',
            name='industry_code',
        ),
        migrations.RemoveField(
            model_name='account',
            name='market_code',
        ),
        migrations.RemoveField(
            model_name='account',
            name='sales_person',
        ),
        migrations.RemoveField(
            model_name='marketcode',
            name='account',
        ),
        migrations.RemoveField(
            model_name='companycontact',
            name='account',
        ),
        migrations.RemoveField(
            model_name='industrycode',
            name='account',
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='status',
        ),
        migrations.RemoveField(
            model_name='companycontact',
            name='department',
        ),
        migrations.DeleteModel(
            name='AccountNote',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='SalesPerson',
        ),
        migrations.DeleteModel(
            name='MarketCode',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='IndustryCode',
        ),
        migrations.DeleteModel(
            name='AccountType',
        ),
        migrations.DeleteModel(
            name='CompanyContact',
        ),
        migrations.DeleteModel(
            name='CompanyDepartment',
        ),
    ]
