# Generated by Django 5.2.4 on 2025-08-24 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adAdmin', '0003_accountnote_companydepartment_customer_publication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=100)),
                ('name', models.CharField(default=None, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'advertising_adminadtype',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'advertising_classification',
            },
        ),
        migrations.CreateModel(
            name='ClassifiedCampaignSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('brief', models.CharField(max_length=255)),
                ('advertiser_id', models.IntegerField(null=True)),
                ('advertiser_name', models.CharField(max_length=50, null=True)),
                ('contact_id', models.IntegerField(null=True)),
                ('sales_contact', models.CharField(max_length=50, null=True)),
                ('total_sub', models.IntegerField()),
                ('total_adjustment', models.IntegerField()),
                ('total_campaign', models.IntegerField()),
                ('campaign_detail', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'advertising_campaign_summary',
            },
        ),
        migrations.CreateModel(
            name='ClassifiedAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('recurring', models.BooleanField(default=False)),
                ('recurring_amount', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(default=None, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('notes', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('submitter', models.CharField(default=None, max_length=255)),
                ('status', models.CharField(default='on hold', max_length=50)),
                ('line_count', models.FloatField(default=0.0)),
                ('active', models.BooleanField(default=True)),
                ('size', models.CharField(blank=True, max_length=25, null=True)),
                ('columns', models.IntegerField(default=0)),
                ('column_length', models.IntegerField(default=0)),
                ('unit', models.CharField(blank=True, max_length=25, null=True)),
                ('words', models.CharField(blank=True, max_length=25, null=True)),
                ('page_number', models.CharField(blank=True, max_length=25, null=True)),
                ('overide_total', models.CharField(blank=True, max_length=25, null=True)),
                ('custom_total', models.CharField(blank=True, max_length=25, null=True)),
                ('layout_notes', models.TextField(blank=True, null=True)),
                ('desgin_notes', models.TextField(blank=True, null=True)),
                ('account_notes', models.TextField(blank=True, null=True)),
                ('rate', models.CharField(blank=True, max_length=250, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classified_ads', to='adAdmin.account')),
                ('ad_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifieds.adminadtype')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classifieds.classification')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'advertising_classifiedad',
            },
        ),
        migrations.CreateModel(
            name='ClassifiedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='classified_images/')),
                ('price', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('classified_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='classifieds.classifiedad')),
            ],
            options={
                'verbose_name': 'Classified Image',
                'verbose_name_plural': 'Classified Images',
            },
        ),
        migrations.CreateModel(
            name='ClassifiedSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='classifieds.classification')),
            ],
            options={
                'db_table': 'advertising_classifieds_subcategorys',
            },
        ),
        migrations.CreateModel(
            name='ProductAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_type', models.CharField(choices=[('word_count', 'Word Count Increase'), ('additional_publication', 'Additional Publication')], max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adAdmin.publication')),
            ],
            options={
                'verbose_name': 'Product Addon',
                'verbose_name_plural': 'Product Addons',
                'db_table': 'advertising_classifieds_addons',
                'ordering': ['addon_type', 'label'],
            },
        ),
    ]
