# Generated by Django 5.0.6 on 2025-07-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='description',
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
