# Generated by Django 5.2.4 on 2025-08-24 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adAdmin', '0003_accountnote_companydepartment_customer_publication_and_more'),
        ('classifieds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='classifications',
            field=models.ManyToManyField(blank=True, related_name='publications', to='classifieds.classification'),
        ),
        migrations.AddField(
            model_name='account',
            name='default_publication',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adAdmin.publication'),
        ),
        migrations.AddField(
            model_name='account',
            name='sales_person',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adAdmin.salesperson'),
        ),
    ]
