# Generated by Django 5.2.4 on 2025-09-15 14:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adAdmin', '0004_publication_classifications_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvPubsProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('publication_name', models.CharField(max_length=255)),
                ('country', models.CharField(default='US', max_length=3)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'adv_pubs_profile',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
            ],
            options={
                'verbose_name': 'Company Information',
                'verbose_name_plural': 'Company Information',
                'db_table': 'company_info',
            },
        ),
        migrations.CreateModel(
            name='GLCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('pl_type', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'advertising_glcode',
            },
        ),
        migrations.RemoveField(
            model_name='region',
            name='active',
        ),
        migrations.AddField(
            model_name='region',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='region',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_regions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='region',
            name='publications',
            field=models.ManyToManyField(blank=True, related_name='regions', to='adAdmin.publication'),
        ),
        migrations.AlterField(
            model_name='region',
            name='status',
            field=models.CharField(default='active', max_length=100),
        ),
        migrations.CreateModel(
            name='AdvPubsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('magazine', 'Magazine'), ('newspaper', 'Newspaper'), ('digital', 'Digital')], max_length=20)),
                ('name', models.TextField()),
                ('measurement_unit', models.CharField(blank=True, choices=[('inch', 'Inch'), ('cm', 'CM'), ('pixel', 'Pixel')], max_length=10, null=True)),
                ('fold_orientation', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical'), ('none', 'None')], default='none', max_length=10)),
                ('formats', models.CharField(default='none', max_length=100)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='adAdmin.advpubsprofile')),
            ],
            options={
                'db_table': 'adv_pubs_products',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pricing', models.BooleanField(default=False)),
                ('measurement_type', models.CharField(max_length=100)),
                ('extra_groups', models.CharField(max_length=100)),
                ('tax_category', models.CharField(default='No Tax', max_length=100)),
                ('override_privileges', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('assigned_groups', models.BooleanField(default=True)),
                ('ad_type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('insertion_min', models.CharField(max_length=255)),
                ('insertion_max', models.CharField(max_length=255)),
                ('line_for_ad_min', models.CharField(max_length=255)),
                ('line_for_ad_max', models.CharField(max_length=255)),
                ('insertion_count', models.IntegerField()),
                ('base_cost', models.CharField(max_length=100)),
                ('base_count', models.CharField(max_length=100)),
                ('additional_cost', models.CharField(max_length=100)),
                ('additional_count', models.CharField(max_length=100)),
                ('charge_for', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
                ('product', models.CharField(max_length=255)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adAdmin.account')),
                ('default_gl_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adAdmin.glcode')),
            ],
            options={
                'db_table': 'advertising_rate',
                'permissions': (('can_deactivate_rate', 'Can deactivate rate'), ('can_reactivate_rate', 'Can reactivate rate'), ('can_view_hidden_rates', 'Can view hidden rates'), ('can_lock_rates', 'Can lock rates'), ('can_create_rates', 'Can create rates')),
            },
        ),
        migrations.CreateModel(
            name='AdminAdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=100)),
                ('name', models.CharField(default=None, max_length=255)),
                ('status', models.CharField(default='active', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adTypes', to=settings.AUTH_USER_MODEL)),
                ('publications', models.ManyToManyField(blank=True, related_name='adTypes', to='adAdmin.publication')),
                ('default_rate', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='adAdmin.rate')),
            ],
            options={
                'db_table': 'advertising_adminadtype',
            },
        ),
    ]
